apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 50
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/eva-cosma/ci_cd_lab:1b687679ca52a6c5a9020e77a80cae64b52652a042676ccde5350fa64ca26378
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
